set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_lrsel_o]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_audio_o]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_clk_o]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_data_i]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_sdaudio_o]
set_property IOSTANDARD LVCMOS33 [get_ports play]
set_property IOSTANDARD LVCMOS33 [get_ports play_mem_sel]
set_property IOSTANDARD LVCMOS33 [get_ports record]
set_property IOSTANDARD LVCMOS33 [get_ports record_mem_sel]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports clock]
set_property PACKAGE_PIN H5 [get_ports pdm_data_i]

set_property PACKAGE_PIN J5 [get_ports pdm_clk_o]
set_property PACKAGE_PIN A11 [get_ports pdm_audio_o]
set_property PACKAGE_PIN D12 [get_ports pdm_sdaudio_o]
set_property PACKAGE_PIN P17 [get_ports record]
set_property PACKAGE_PIN M17 [get_ports play]
set_property PACKAGE_PIN J15 [get_ports play_mem_sel]
set_property PACKAGE_PIN L16 [get_ports record_mem_sel]
set_property PACKAGE_PIN N17 [get_ports reset]

set_property PACKAGE_PIN F5 [get_ports pdm_lrsel_o]

set_property PACKAGE_PIN H17 [get_ports playing_now]
set_property PACKAGE_PIN K15 [get_ports recording_now]
set_property IOSTANDARD LVCMOS33 [get_ports recording_now]
set_property IOSTANDARD LVCMOS33 [get_ports playing_now]

set_property PACKAGE_PIN J13 [get_ports idle_state]
set_property IOSTANDARD LVCMOS33 [get_ports idle_state]

set_property PACKAGE_PIN R18 [get_ports temp_led_out]
set_property IOSTANDARD LVCMOS33 [get_ports temp_led_out]
